backend:
  name: test-repo
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'src/data/pages/index.md'
        fields:
          - { label: 'Title - SEO', name: 'title', widget: 'string' }
          - {
              label: 'Description - SEO',
              name: 'description',
              widget: 'string',
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Drawer'
            name: 'drawer'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
